export enum DashboardStage {
  NO_ORDER = "NO_ORDER",

  ORDER_CONFIRMED = "ORDER_CONFIRMED",

  VEHICLE_ASSIGNED = "VEHICLE_ASSIGNED",

  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",

  DELIVERED = "DELIVERED",

  PAYMENT_PENDING = "PAYMENT_PENDING",

  READY_FOR_TOMORROW = "READY_FOR_TOMORROW",
}