export enum DashboardState {
  NO_ORDER = "NO_ORDER",

  AFTER_CUTOFF = "AFTER_CUTOFF",

  ORDER_CONFIRMED = "ORDER_CONFIRMED",

  FARM_ALLOCATED = "FARM_ALLOCATED",

  PREPARING = "PREPARING",

  VEHICLE_ASSIGNED = "VEHICLE_ASSIGNED",

  OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",

  DELIVERED = "DELIVERED",

  PAYMENT_PENDING = "PAYMENT_PENDING",

  READY_FOR_TOMORROW_ORDER = "READY_FOR_TOMORROW_ORDER",

  SCHEDULE_CONFIRMATION_PENDING = "SCHEDULE_CONFIRMATION_PENDING",

  FUTURE_ORDER_CONFIRMED = "FUTURE_ORDER_CONFIRMED",
}